name: build
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.1'
      - run: make build
      - uses: actions/upload-artifact@v2
        with:
          name: systemd_exporter
          path: systemd_exporter
      - run: make test
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: systemd_exporter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

